MVC_AppleLaLa_Admin/Controllers/Customer_couponController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCDataLibrary.DB_Model;
using PagedList;

namespace MVC_AppleLaLa_Admin.Controllers
{
    //[Authorize(Users = "applelala")]
    public class Customer_couponController : Controller
    {
        private AppleLaLaModel db = new AppleLaLaModel();

        // GET: Customer_coupon
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CouponNameSortParm = String.IsNullOrEmpty(sortOrder) ? "first_desc" : "";
            ViewBag.CustomerAccountSortParm = sortOrder == "last" ? "last_desc" : "last";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var workers = from w in db.Customer_coupon
                          select w;
            if (!string.IsNullOrEmpty(searchString))
            {
                workers = workers.Where(w => w.Coupon.Coupon_name.Contains(searchString)
                || w.Customer.Account.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "first_desc":
                    workers = workers.OrderByDescending(w => w.Coupon.Coupon_name);
                    break;
                case "last_desc":
                    workers = workers.OrderByDescending(w => w.Customer.Account);
                    break;
                case "last":
                    workers = workers.OrderBy(w => w.Customer.Account);
                    break;
                default:
                    workers = workers.OrderBy(w => w.Coupon.Coupon_name);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(workers.ToPagedList(pageNumber, pageSize));
        }

        // GET: Customer_coupon/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer_coupon customer_coupon = db.Customer_coupon.Find(id);
            if (customer_coupon == null)
            {
                return HttpNotFound();
            }
            return View(customer_coupon);
        }

        // GET: Customer_coupon/Create
        public ActionResult Create()
        {
            ViewBag.Coupon_id = new SelectList(db.Coupon, "Coupon_id", "Coupon_name");
            ViewBag.Cust_id = new SelectList(db.Customer, "Cust_id", "Account");
            return View();
        }

        // POST: Customer_coupon/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Cust_id,Coupon_id,End_day,Start_day")] Customer_coupon customer_coupon)
        {
            if (ModelState.IsValid)
            {
                db.Customer_coupon.Add(customer_coupon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Coupon_id = new SelectList(db.Coupon, "Coupon_id", "Coupon_name", customer_coupon.Coupon_id);
            ViewBag.Cust_id = new SelectList(db.Customer, "Cust_id", "Account", customer_coupon.Cust_id);
            return View(customer_coupon);
        }

        // GET: Customer_coupon/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer_coupon customer_coupon = db.Customer_coupon.Find(id);
            if (customer_coupon == null)
            {
                return HttpNotFound();
            }
            ViewBag.Coupon_id = new SelectList(db.Coupon, "Coupon_id", "Coupon_name", customer_coupon.Coupon_id);
            ViewBag.Cust_id = new SelectList(db.Customer, "Cust_id", "Account", customer_coupon.Cust_id);
            return View(customer_coupon);
        }

        // POST: Customer_coupon/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Cust_id,Coupon_id,End_day,Start_day")] Customer_coupon customer_coupon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer_coupon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Coupon_id = new SelectList(db.Coupon, "Coupon_id", "Coupon_name", customer_coupon.Coupon_id);
            ViewBag.Cust_id = new SelectList(db.Customer, "Cust_id", "Account", customer_coupon.Cust_id);
            return View(customer_coupon);
        }

        // GET: Customer_coupon/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer_coupon customer_coupon = db.Customer_coupon.Find(id);
            if (customer_coupon == null)
            {
                return HttpNotFound();
            }
            return View(customer_coupon);
        }

        // POST: Customer_coupon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer_coupon customer_coupon = db.Customer_coupon.Find(id);
            db.Customer_coupon.Remove(customer_coupon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_AppleLaLa_Admin/Views/Customer_coupon/Create.cshtml
@model MVCDataLibrary.DB_Model.Customer_coupon

@{
    ViewBag.Title = "Create";
}

@section topCSS{
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
}

<h2>新增客戶優惠券資料</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cust_id, "客戶編號", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cust_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cust_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coupon_id, "優惠券編號", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Coupon_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Coupon_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End_day, "結束日期", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End_day, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.End_day, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start_day, "開始日期", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start_day, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start_day, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn create_btn" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_AppleLaLa_Admin/Views/Customer_coupon/Delete.cshtml
@model MVCDataLibrary.DB_Model.Customer_coupon

@{
    ViewBag.Title = "Delete";
}

@section topCSS {
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
}

<h2>刪除客戶優惠券</h2>

<h3>確定要刪除?</h3>
<div>
    <hr />
    <dl class="dl-horizontal horizontal">
        <dt>
            優惠券名稱
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coupon.Coupon_name)
        </dd>

        <dt>
            帳戶
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Account)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions">
            <input type="submit" value="確認刪除" class="btn del_btn confirm_del" />
        </div>
    }

    <div>
        @Html.ActionLink("回到列表", "Index")
    </div>
</div>

MVC_AppleLaLa_Admin/Views/Customer_coupon/Details.cshtml
@model MVCDataLibrary.DB_Model.Customer_coupon

@{
    ViewBag.Title = "Details";
}

@section topCSS{
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
}

<h2>客戶優惠券詳細資料</h2>

<div>
    <hr />
    <dl class="dl-horizontal horizontal">
        <dt>
            優惠券名稱
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coupon.Coupon_name)
        </dd>

        <dt>
            帳戶
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Account)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("前往修改資料", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("回到列表", "Index")
</p>

MVC_AppleLaLa_Admin/Views/Customer_coupon/Edit.cshtml
@model MVCDataLibrary.DB_Model.Customer_coupon

@{
    ViewBag.Title = "Edit";
}

@section topCSS{
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
}

<h2>修改客戶優惠券</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal horizontal mx-auto">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Cust_id)

        @Html.HiddenFor(model => model.Coupon_id)

        @Html.HiddenFor(model => model.End_day)

        @Html.HiddenFor(model => model.Start_day)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn save_btn" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_AppleLaLa_Admin/Views/Customer_coupon/Index.cshtml
@*@model IEnumerable<MVCDataLibrary.DB_Model.Customer_coupon>*@
@using MVCDataLibrary.DB_Model;
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<Customer_coupon>

@{
    ViewBag.Title = "Index";
}

@section topCSS{
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
}

<div class="col-md-12 col-sm-12 table_all">
    <div class="x_panel table">
        <div>
            <h1 class="text-center h1_title"><a class="h1_title" href="/Customer_coupon/Index">客戶優惠券</a></h1>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    @using (Html.BeginForm("Index", "Customer_coupon", FormMethod.Get))
                    {
                        <div class="d-flex">
                            @Html.TextBox("SearchString", "", new { @class = "search_text" })
                            <input type="submit" value="查詢" class="searching btn edit_btn" />
                        </div>
                    }
                </li>
                <li>
                    <a href="/Customer_coupon/Create" title="新增資料"><i class="fas fa-plus"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" title="其他連結"><i class="fas fa-link"></i></a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/Coupons/Index">優惠券</a>
                        <a class="dropdown-item" href="/Customer_coupon/Index">客戶優惠券</a>
                    </div>
                </li>
                <li>
                    <a class="collapse-link" title="收縮表格"><i class="fa fa-chevron-up"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>@Html.ActionLink("優惠券名稱", "Index", new { sortOrder = ViewBag.CouponNameSortParm })</th>
                        <th>@Html.ActionLink("帳戶", "Index", new { sortOrder = ViewBag.CustomerAccountSortParm })</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count() == 0)
                    {
                        <tr>
                            <td colspan="3" style="color:red;">
                                暫無資料
                            </td>
                        </tr>
                    }
                    else
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.ActionLink(@item.Coupon.Coupon_name, "Details", new { /* id=item.PrimaryKey */ })
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Customer.Account)
                                </td>
                                <td>
                                    @Html.ActionLink("修改", "Edit", new { /* id=item.PrimaryKey */ }, new { @class = "btn edit_btn" })
                                    @Html.ActionLink("刪除", "Delete", new { /* id=item.PrimaryKey */ }, new { @class = "btn del_btn" })
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            第 @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount 頁
            @Html.PagedListPager(Model, page => Url.Action("Index", "Customer_coupon", new { page = page }))
        </div>
    </div>
</div>