MVC_AppleLaLa_Admin/Controllers/BannersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Imgur.API;
using Imgur.API.Authentication.Impl;
using Imgur.API.Endpoints.Impl;
using Imgur.API.Models;
using MVC_AppleLaLa_Admin.Services;
using MVCDataLibrary.DB_Model;

namespace MVC_AppleLaLa_Admin.Controllers
{
    //[Authorize(Users = "applelala")]
    public class BannersController : Controller
    {
        private AppleLaLaModel db = new AppleLaLaModel();

        // GET: Banners
        public ActionResult Index(string searching)
        {
            return View(db.Banner.Where(x => x.Title.Contains(searching) || x.Sut_title.Contains(searching) || x.Text.Contains(searching) || searching == null).ToList());
        }

        // GET: Banners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Banner banner = db.Banner.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // GET: Banners/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Banners/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Banner1,Title,Sut_title,Text,Banner_photo_url,Last_updata_date")] Banner banner)
        {
            if (ModelState.IsValid)
            {
                BannerService service = new BannerService();
                var result = service.Create(banner);
                if (result.IsSuccessful)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(banner);
        }

        // GET: Banners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Banner banner = db.Banner.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // POST: Banners/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Banner1,Title,Sut_title,Text,Banner_photo_url,Last_updata_date")] Banner banner)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(banner).State = EntityState.Modified;
                //db.SaveChanges();
                BannerService service = new BannerService();
                var result = service.Edit(banner);
                if (result.IsSuccessful)
                {
                    return RedirectToAction("Index");
                }
                
            }
            return View(banner);
        }

        // GET: Banners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Banner banner = db.Banner.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // POST: Banners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Banner banner = db.Banner.Find(id);
            db.Banner.Remove(banner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_AppleLaLa_Admin/Views/Banners/Create.cshtml
@model MVCDataLibrary.DB_Model.Banner

@{
    ViewBag.Title = "Create";
}

@section topCSS{
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
}

<h2>新增資料</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="card mb-3">
            <div class="row">
                <div class="col-md-4">

                    <img class="card-img show_img" src="#" alt="" />

                </div>
                <div class="col-md-8">

                    <div class="card-body">

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, "標題", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Sut_title, "副標題", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Sut_title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Sut_title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Text, "文本", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group" id="upload">
                            <label class="control-label col-md-2" for="upload">選擇上傳圖檔</label>
                            <div class="col-md-10">
                                <input id="upload" type="file" accept="image/*" v-on:change="showFile">
                                <!-- 上傳按鈕 -->
                                <button class="btn upload_btn mt-1" type="button" v-on:click="submit">上傳</button>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="新增" class="btn create_btn" />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表", "Index")
</div>


@section endJS{
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script>
        const id = '21a0ed102aa145f'; // 填入 App 的 Client ID
        const token = '9acfbce0e72f307b007600627630c1eb3618d545'; // 填入 token
        const album = 'LtQupwK';

        const upload = new Vue({
            el: '#upload',
            data: {
                album: album, // 若要指定傳到某個相簿，就填入相簿的 ID
                file: null, // 準備拿 input type="file" 的值
                fs: {
                    name: '', // input的圖檔名稱
                    thumbnail: null, // input的圖片縮圖
                    size: null // input的圖片大小
                },
            },
            methods: {
                showFile(e) {
                    this.file = e.target.files[0]; // input type="file" 的值
                    this.fs.name = this.file.name; // input的圖檔名稱
                    this.fs.size = Math.floor(this.file.size * 0.001) + 'KB'; // input的圖片大小
                    this.fs.thumbnail = window.URL.createObjectURL(this.file); // input的圖片縮圖
                    this.title = this.fs.name; // 預設 input 的圖檔名稱為圖片上傳時的圖片標題
                },
                submit() {
                    let settings = {
                        async: false,
                        crossDomain: true,
                        processData: false,
                        contentType: false,
                        type: 'POST',
                        @*url:'@Url.Action("Upload", "Banners")',*@
                        url: 'https://api.imgur.com/3/image/',
                        headers: {
                            Authorization: 'Bearer ' + token
                            // Authorization: "Client-ID " + id
                        },
                        mimeType: 'multipart/form-data'
                    };
                    //api要的格式
                    let form = new FormData();
                    form.append('image', this.file);
                    form.append('title', this.title);
                    form.append('description', this.des);
                    form.append('album', album); // 有要指定的相簿就加這行
                    settings.data = form;

                    $.ajax(settings).done(function (res) {
                        var imgdata = JSON.parse(res);
                        var link = imgdata.data.link
                        ChangeImg(link);
                        /*console.log(ooxx);*/ // 可以看見上傳成功後回的值
                        alert('上傳完成，稍待一會兒就可以在底部的列表上看見了。')
                    });
                }
            }
        });

        function ChangeImg(value) {
            $('.show_img').attr('src', value);
            $('#Banner_photo_url').attr('value', value)
        }

    </script>

}

MVC_AppleLaLa_Admin/Views/Banners/Delete.cshtml
@model MVCDataLibrary.DB_Model.Banner

@{
    ViewBag.Title = "Delete";
}

@section topCSS {
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
}

<h2>刪除資料</h2>

<h3>確定要刪除?</h3>
<div>
    <hr />
    <dl class="dl-horizontal horizontal">
        <dt>
            標題
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            副標題
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sut_title)
        </dd>

        <dt>
            文本
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            圖片連結
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.Banner_photo_url)" alt="暫無" style="width:400px;height:400px" />
        </dd>
        <dd>
            <a href="@Html.DisplayFor(model => model.Banner_photo_url)">@Html.DisplayFor(model => model.Banner_photo_url)</a>
        </dd>

        <dt>
            最後更新日期
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Last_updata_date)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions">
            <input type="submit" value="確認刪除" class="btn del_btn confirm_del" />
        </div>
    }

    <div>
        @Html.ActionLink("回到列表", "Index")
    </div>
</div>

MVC_AppleLaLa_Admin/Views/Banners/Details.cshtml
@model MVCDataLibrary.DB_Model.Banner

@{
    ViewBag.Title = "Details";
}

@section topCSS{
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
}

<h2>詳細資料</h2>

<div>
    <hr />
    <dl class="dl-horizontal horizontal">
        <dt>
            標題
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            副標題
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sut_title)
        </dd>

        <dt>
            文本
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            圖片連結
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.Banner_photo_url)" alt="暫無" style="width:400px;height:400px" />
        </dd>
        <dd>
            <a href="@Html.DisplayFor(model => model.Banner_photo_url)">@Html.DisplayFor(model => model.Banner_photo_url)</a>
        </dd>

        <dt>
            最後更新日期
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Last_updata_date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("前往修改資料", "Edit", new { id = Model.Banner1 }) |
    @Html.ActionLink("回到列表", "Index")
</p>

MVC_AppleLaLa_Admin/Views/Banners/Edit.cshtml
@model MVCDataLibrary.DB_Model.Banner

@{
    ViewBag.Title = "Edit";
}

@section topCSS{
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
}

<h2>修改資料</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal horizontal mx-auto">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Banner1)
        <div class="card mb-3">
            <div class="row">
                <div class="col-md-4">

                    <img src="@Model.Banner_photo_url" class="card-img show_img" alt="...">

                </div>
                <div class="col-md-8">

                    <div class="card-body">

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, "標題", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Sut_title, "副標題", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Sut_title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Sut_title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Text, "文本", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Banner_photo_url, "圖片連結", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Banner_photo_url, new { htmlAttributes = new { @class = "form-control", @readonly = "value" } })
                                @Html.ValidationMessageFor(model => model.Banner_photo_url, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group" id="upload">
                            <label class="control-label col-md-2" for="upload">選擇上傳圖檔</label>
                            <div class="col-md-10">
                                <input id="upload" type="file" accept="image/*" v-on:change="showFile">
                                <!-- 上傳按鈕 -->
                                <button class="btn upload_btn mt-1" type="button" v-on:click="submit">上傳</button>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="儲存" class="btn save_btn" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("回到列表", "Index")
</div>

@section endJS{
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script>
        const id = '21a0ed102aa145f'; // 填入 App 的 Client ID
        const token = '9acfbce0e72f307b007600627630c1eb3618d545'; // 填入 token
        const album = 'LtQupwK';

        const upload = new Vue({
            el: '#upload',
            data: {
                album: album, // 若要指定傳到某個相簿，就填入相簿的 ID
                file: null, // 準備拿 input type="file" 的值
                fs: {
                    name: '', // input的圖檔名稱
                    thumbnail: null, // input的圖片縮圖
                    size: null // input的圖片大小
                },
            },
            methods: {
                showFile(e) {
                    this.file = e.target.files[0]; // input type="file" 的值
                    this.fs.name = this.file.name; // input的圖檔名稱
                    this.fs.size = Math.floor(this.file.size * 0.001) + 'KB'; // input的圖片大小
                    this.fs.thumbnail = window.URL.createObjectURL(this.file); // input的圖片縮圖
                    this.title = this.fs.name; // 預設 input 的圖檔名稱為圖片上傳時的圖片標題
                },
                submit() {
                    let settings = {
                        async: false,
                        crossDomain: true,
                        processData: false,
                        contentType: false,
                        type: 'POST',
                        url: 'https://api.imgur.com/3/image/',
                        headers: {
                            Authorization: 'Bearer ' + token
                            // Authorization: "Client-ID " + id
                        },
                        mimeType: 'multipart/form-data'
                    };

                    //api要的格式
                    let form = new FormData();
                    form.append('image', this.file);
                    form.append('title', this.title);
                    form.append('description', this.des);
                    form.append('album', album); // 有要指定的相簿就加這行
                    settings.data = form;

                    $.ajax(settings).done(function (res) {
                        var imgdata = JSON.parse(res);
                        var link = imgdata.data.link
                        ChangeImg(link);
                        /*console.log(ooxx);*/ // 可以看見上傳成功後回的值

                        alert('上傳完成，稍待一會兒就可以在底部的列表上看見了。')
                    });
                }
            }
        });

        function ChangeImg(value) {
            $('.show_img').attr('src', value);
            $('#Banner_photo_url').attr('value', value)
        }

    </script>

}

MVC_AppleLaLa_Admin/Views/Banners/Index.cshtml
@model IEnumerable<MVCDataLibrary.DB_Model.Banner>

@{
    ViewBag.Title = "Index";
}

@section topCSS{
    <link href="~/Assets/css/tables.css" rel="stylesheet" />
}

<ul class="nav navbar-right panel_toolbox">
    <li>
        @using (Html.BeginForm("Index", "Banners", FormMethod.Get))
        {
        <div class="mt-1 px-auto">
            @Html.TextBox("searching", "", new { @class = "search_text" })
            <input type="submit" value="查詢" class="searching btn edit_btn" />
            <a href="/Banners/Create" class="pr-0" title="新增資料"><i class="fas fa-plus"></i></a>
        </div>
        }
    </li>
</ul>
<div class="clearfix"></div>
@if (Model.Count() == 0)
{
    <tr>
        <td colspan="1" style="color:red;">
            暫無資料
        </td>
    </tr>
}
else
{
    foreach (var el in Model)
    {
        <div class="card mb-3">
            <div class="row">
                <div class="col-md-4">

                    <img src="@el.Banner_photo_url" class="card-img d-block h-100 overflow-hidden" alt="暫無">

                </div>
                <div class="col-md-8">
                    <div class="card-body banner_body">
                        <h3 class="card-title">@el.Title</h3>
                        <h5>@el.Sut_title</h5>
                        <p class="card-text">
                            @el.Text
                        </p>
                        <p class="card-text"><small class="text-muted">@el.Last_updata_date</small></p>
                        @Html.ActionLink("修改", "Edit", new { id = el.Banner1 }, new { @class = "btn edit_btn" })
                        @Html.ActionLink("詳細資料", "Details", new { id = el.Banner1 }, new { @class = "btn edit_btn" })
                        @Html.ActionLink("刪除", "Delete", new { id = el.Banner1 }, new { @class = "btn del_btn" })
                    </div>
                </div>
            </div>
        </div>
    }
}